name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -euo pipefail
            if [ ! -d "/opt/monitor-stack/.git" ]; then
              git clone ${{ secrets.REPO_URL }} /opt/monitor-stack
            fi

            cd /opt/monitor-stack
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans